### ISSUE TITLE
This is more of a question

### ISSUE THREAD

**Issue by jamierytlewski** [Advsol/Roanoke_Responsive#1]
How much addition do you plan on doing to this theme or is this going to be a super bare bones? The reason I ask is that I do notice that bigger chunks were added a few days ago, and I see things such as the hero/slider/carousel are missing.

**Comment by RoboAndie** [comment]
Hi Jaimie,

I added some chunks recently because there were some changes made for the interim update. I did not add styles for the hero/slider/carousel because the styles for the carousel iPart are included in UltraWave, which is a requirement for this theme to work. (UltraWave is added automatically based on the ThemeSettings.xml file, which the system uses to determine which version of UltraWave to include.)

Does that answer your question? Is there something specific that you're looking for?

**Comment by jamierytlewski** [comment]
Yes it answers it partially, but now I have a few more questions. We are new to iMIS. We are not a fan of any of the themes such as Austin, London and all the different cities. How is Roanoke different and is there going to be additions/subtractions to this. 

Also, is this something that would say be ready to go. I tried plugging it in and seemed 1/2 barebones, but not fully. I see the top nav is barebones, but the right side nav is not. 

Lastly, if there's any code that could be cleaned are you accepting pull requests? An example I can give is: https://github.com/Advsol/Roanoke_Responsive/blob/master/Roanoke_Responsive/99-Roanoke_Responsive.css#L887

`margin-bottom` gets used twice. I see the comment afterwards, but there's no sense in using `margin-bottom` twice. There's some other pieces that can be improved upon and is this project something that has guidelines to that?
